# Define el nombre del ejecutable
NAME = complex

# Define el compilador a utilizar
COMPILER = cc

# Define las flags del compilador
FLAGS = -Wall -Werror -Wextra

# Define el comando para eliminar archivos
RM = rm -rf

# Define la ubicación de las librerías
LIB_FOLDER = inc

# Define la ubicación de la librería printf
LIB_PRINTF_FOLDER = .$(LIB_FOLDER)/printf

# Define el archivo de la librería printf
LIB_PRINTF = $(LIB_PRINTF_FOLDER)/libftprintf.a

# Define el comando para llamar al Makefile de printf
LIBFT_MAKEFILE = make -C $(LIB_PRINTF_FOLDER)

# Define los includes para la compilación
INCLUDES = -I$(LIB_PRINTF_FOLDER)

# Define la ruta a las librerías
libpath = -L$(LIB_PRINTF_FOLDER)

# Define las librerías a enlazar
LIBS = -lftprintf

# Define la carpeta donde están los archivos fuente
SRC_FOLDER = src/

# Lista los archivos fuente
SRC_FILES = main.c \

# Concatena la ruta con los nombres de archivos

# Genera los nombres de los archivos objeto

# -- RULES -- #
# Regla principal que compila el programa y la librería printf
# Regla patrón para compilar cada archivo .c a .o
# Enlaza los objetos con la librería para crear el ejecutable
# Elimina los archivos objeto y limpia printf
# Limpieza completa: elimina objetos y ejecutable
# Recompila todo desde cero
# Declara reglas que no generan archivos

# -- UTILS -- #
# Ejecuta el programa

# -- LIBRARIES -- #

# Compila la librería printf
# Recompila la librería printf
# Limpia los objetos de printf
# Limpia completamente printf
